#! /bin/bash

if [[ $# -lt 3 ]]; then
    echo "Usage: kegbuild <directory> <keg-folder> <output.keg>"
    exit 1
fi

ORIG_DIR="$PWD"
KEG_DIR="$(cd "$1" && cd "$2" && pwd)" || { echo "Error: Could not find '$1/$2'"; exit 1; }
cd "$KEG_DIR"
zip -9 -r /tmp/kegbuild_output.zip *
mv /tmp/kegbuild_output.zip "$ORIG_DIR/$3"
cd "$ORIG_DIR"
